image: docker:latest

build-master:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

deploy-master:
  stage: deploy
  script:
    - apk update && apk add curl
    - curl -XPOST "${SERVICE_WEBHOOK}"
  only:
    - master
